l3leaf_node_group: DC1_LEAF3
switch_platform: vEOS-LAB
switch_bgp_as: 65103
leaf_id: 5
switch_mgmt_ip: 10.73.3.7/16
leaf_evpn_services_l2_only: false
switch_router_id: 192.168.255.7
switch_evpn_role: client
switch_evpn_route_servers:
- DC1-SPINE01
- DC1-SPINE02
switch_evpn_route_clients: []
leaf_filter_tenants:
- all
leaf_filter_tags:
- all
leaf_allowed_vrfs:
- Tenant_A_APP_Zone
- Tenant_A_DB_Zone
- Tenant_A_OP_Zone
- Tenant_A_WAN_Zone
- Tenant_A_WEB_Zone
- Tenant_B_OP_Zone
- Tenant_B_WAN_Zone
- Tenant_C_OP_Zone
- Tenant_C_WAN_Zone
leaf_allowed_svis:
- 130
- 131
- 140
- 141
- 110
- 111
- 112
- 150
- 120
- 121
- 210
- 211
- 250
- 310
- 311
- 350
leaf_allowed_vlans:
- 130
- 131
- 140
- 141
- 110
- 111
- 112
- 150
- 120
- 121
- 160
- 161
- 210
- 211
- 250
- 310
- 311
- 350
leaf_mlag: false
service_routing_protocols_model: multi-agent
ip_routing: true
hardware_counters: null
daemon_terminattr:
  ingestgrpcurl:
    ips:
    - 10.83.31.63
    port: 9910
  ingestauth_key: Arista123
  ingestvrf: MGMT
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: false
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
event_monitor: null
event_handlers: null
load_interval:
  default: 5
queue_monitor_length: null
name_server:
  source:
    vrf: MGMT
  nodes:
  - 10.73.0.1
ntp_server:
  local_interface:
    vrf: MGMT
    interface: Management1
  nodes:
  - 10.73.0.1
redundancy: null
spanning_tree:
  mode: mstp
  mst_instances:
    '0':
      priority: 4096
aaa_authorization:
  exec:
    default: local
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$qDzD2KQXoyPAYiKW$44OfXUXfvwKXJZcJ4/MOljDk8HxONlzJHjcYGPNxeU0JHvB2fyVBBdhph239vRrFcobF5H3/5J2etJljjhhiQ.
  ansible:
    privilege: 15
    role: network-admin
    sha512_password: $6$/OcMpqcR8opsfwLC$Ui9GUIQH2WcykVQKsbZccT53QN./PWbd2Zn5pipvoqbTJMSE9SWwJnoN5eGq2A/bM9wMcoMrP.nyUDAbgZcLF0
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$qgSkkn4vOILubEVA$eGaW0WVo6ZooKdSAfNMUpZKZ1hSn1cHh5xYIPFsB83C.UIOPg0TRRBoPypKKgEpmhdPdbgOQjh7IazXhtv.191
clock: null
vlans:
  130:
    tenant: Tenant_A
    name: Tenant_A_APP_Zone_1
  131:
    tenant: Tenant_A
    name: Tenant_A_APP_Zone_2
  140:
    tenant: Tenant_A
    name: Tenant_A_DB_BZone_1
  141:
    tenant: Tenant_A
    name: Tenant_A_DB_Zone_2
  110:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_1
  111:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_2
  112:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_3
  150:
    tenant: Tenant_A
    name: Tenant_A_WAN_Zone_1
  120:
    tenant: Tenant_A
    name: Tenant_A_WEB_Zone_1
  121:
    tenant: Tenant_A
    name: Tenant_A_WEBZone_2
  160:
    tenant: Tenant_A
    name: Tenant_A_VMOTION
  161:
    tenant: Tenant_A
    name: Tenant_A_NFS
  210:
    tenant: Tenant_B
    name: Tenant_B_OP_Zone_1
  211:
    tenant: Tenant_B
    name: Tenant_B_OP_Zone_2
  250:
    tenant: Tenant_B
    name: Tenant_B_WAN_Zone_1
  310:
    tenant: Tenant_C
    name: Tenant_C_OP_Zone_1
  311:
    tenant: Tenant_C
    name: Tenant_C_OP_Zone_2
  350:
    tenant: Tenant_C
    name: Tenant_C_WAN_Zone_1
vrfs:
  MGMT:
    ip_routing: false
  Tenant_A_APP_Zone:
    tenant: Tenant_A
    ip_routing: true
  Tenant_A_DB_Zone:
    tenant: Tenant_A
    ip_routing: true
  Tenant_A_OP_Zone:
    tenant: Tenant_A
    ip_routing: true
  Tenant_A_WAN_Zone:
    tenant: Tenant_A
    ip_routing: true
  Tenant_A_WEB_Zone:
    tenant: Tenant_A
    ip_routing: true
  Tenant_B_OP_Zone:
    tenant: Tenant_B
    ip_routing: true
  Tenant_B_WAN_Zone:
    tenant: Tenant_B
    ip_routing: true
  Tenant_C_OP_Zone:
    tenant: Tenant_C
    ip_routing: true
  Tenant_C_WAN_Zone:
    tenant: Tenant_C
    ip_routing: true
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3
port_channel_interfaces: null
ethernet_interfaces:
  Ethernet1:
    peer: DC1-SPINE01
    peer_interface: Ethernet5
    peer_type: spine
    description: P2P_LINK_TO_DC1-SPINE01_Ethernet5
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.17/31
  Ethernet2:
    peer: DC1-SPINE02
    peer_interface: Ethernet5
    peer_type: spine
    description: P2P_LINK_TO_DC1-SPINE02_Ethernet5
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.19/31
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 192.168.255.7/32
  Loopback1:
    description: VTEP_VXLAN_Tunnel_Source
    shutdown: false
    ip_address: 192.168.254.7/32
  Loopback100:
    description: Tenant_A_OP_Zone_VTEP_DIAGNOSTICS
    shutdown: false
    vrf: Tenant_A_OP_Zone
    ip_address: 10.255.1.7/32
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 10.73.3.7/16
    gateway: 10.73.0.1
vlan_interfaces:
  Vlan130:
    tenant: Tenant_A
    tags:
    - app
    - erp1
    description: Tenant_A_APP_Zone_1
    shutdown: false
    vrf: Tenant_A_APP_Zone
  Vlan131:
    tenant: Tenant_A
    tags:
    - app
    description: Tenant_A_APP_Zone_2
    shutdown: false
    vrf: Tenant_A_APP_Zone
    ip_address_virtual: 10.1.31.254/24
  Vlan140:
    tenant: Tenant_A
    tags:
    - db
    - erp1
    description: Tenant_A_DB_BZone_1
    shutdown: false
    vrf: Tenant_A_DB_Zone
    ip_address_virtual: 10.1.40.1/24
  Vlan141:
    tenant: Tenant_A
    tags:
    - db
    description: Tenant_A_DB_Zone_2
    shutdown: false
    vrf: Tenant_A_DB_Zone
    ip_address_virtual: 10.1.41.1/24
  Vlan110:
    tenant: Tenant_A
    tags:
    - opzone
    description: Tenant_A_OP_Zone_1
    shutdown: false
    vrf: Tenant_A_OP_Zone
    ip_address_virtual: 10.1.10.1/24
  Vlan111:
    tenant: Tenant_A
    tags:
    - opzone
    description: Tenant_A_OP_Zone_2
    shutdown: false
    vrf: Tenant_A_OP_Zone
    ip_address_virtual: 10.1.11.1/24
  Vlan112:
    tenant: Tenant_A
    tags:
    - opzone
    description: Tenant_A_OP_Zone_3
    shutdown: false
    vrf: Tenant_A_OP_Zone
    ip_address_virtual: 10.1.12.254/24
  Vlan150:
    tenant: Tenant_A
    tags:
    - wan
    description: Tenant_A_WAN_Zone_1
    shutdown: false
    vrf: Tenant_A_WAN_Zone
    ip_address_virtual: 10.1.40.1/24
  Vlan120:
    tenant: Tenant_A
    tags:
    - web
    - erp1
    description: Tenant_A_WEB_Zone_1
    shutdown: false
    vrf: Tenant_A_WEB_Zone
  Vlan121:
    tenant: Tenant_A
    tags:
    - web
    description: Tenant_A_WEBZone_2
    shutdown: false
    vrf: Tenant_A_WEB_Zone
    ip_address_virtual: 10.1.21.1/24
  Vlan210:
    tenant: Tenant_B
    tags:
    - opzone
    description: Tenant_B_OP_Zone_1
    shutdown: false
    vrf: Tenant_B_OP_Zone
  Vlan211:
    tenant: Tenant_B
    tags:
    - opzone
    description: Tenant_B_OP_Zone_2
    shutdown: false
    vrf: Tenant_B_OP_Zone
    ip_address_virtual: 10.2.11.1/24
  Vlan250:
    tenant: Tenant_B
    tags:
    - wan
    description: Tenant_B_WAN_Zone_1
    shutdown: false
    vrf: Tenant_B_WAN_Zone
    ip_address_virtual: 10.2.50.1/24
  Vlan310:
    tenant: Tenant_C
    tags:
    - opzone
    description: Tenant_C_OP_Zone_1
    shutdown: false
    vrf: Tenant_C_OP_Zone
  Vlan311:
    tenant: Tenant_C
    tags:
    - opzone
    description: Tenant_C_OP_Zone_2
    shutdown: false
    vrf: Tenant_C_OP_Zone
  Vlan350:
    tenant: Tenant_C
    tags:
    - wan
    description: Tenant_C_WAN_Zone_1
    shutdown: false
    vrf: Tenant_C_WAN_Zone
vxlan_tunnel_interface:
  Vxlan1:
    description: DC1-LEAF3A_VTEP
    source_interface: Loopback1
    vxlan_udp_port: 4789
    vxlan_vni_mappings:
      vlans:
        130:
          vni: 10130
        131:
          vni: 10131
        140:
          vni: 10140
        141:
          vni: 10141
        110:
          vni: 10110
        111:
          vni: 50111
        112:
          vni: 50112
        150:
          vni: 10150
        120:
          vni: 10120
        121:
          vni: 10121
        160:
          vni: 55160
        161:
          vni: 10161
        210:
          vni: 20210
        211:
          vni: 20211
        250:
          vni: 20250
        310:
          vni: 30310
        311:
          vni: 30311
        350:
          vni: 30350
      vrfs:
        Tenant_A_APP_Zone:
          vni: 12
        Tenant_A_DB_Zone:
          vni: 13
        Tenant_A_OP_Zone:
          vni: 10
        Tenant_A_WAN_Zone:
          vni: 14
        Tenant_A_WEB_Zone:
          vni: 11
        Tenant_B_OP_Zone:
          vni: 20
        Tenant_B_WAN_Zone:
          vni: 21
        Tenant_C_OP_Zone:
          vni: 30
        Tenant_C_WAN_Zone:
          vni: 31
tcam_profile: null
platform: null
mac_address_table: null
ip_virtual_router_mac_address: 00:1c:73:00:dc:01
virtual_source_nat_vrfs:
  Tenant_A_OP_Zone:
    ip_address: 10.255.1.7
ip_igmp_snooping:
  globally_enabled: true
  vlans: null
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.73.0.1
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 192.168.255.0/24 eq 32
      20:
        action: permit 192.168.254.0/24 eq 32
route_maps:
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bgp:
  as: 65103
  router_id: 192.168.255.7
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  - maximum-paths 4 ecmp 4
  peer_groups:
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      remote_as: 65001
      password: AQQvKeimxJu+uGQ/yYvv9w==
      maximum_routes: 12000
      send_community: true
    EVPN-OVERLAY-PEERS:
      type: evpn
      update_source: Loopback0
      bfd: true
      ebgp_multihop: '3'
      password: q+VNViP5i4rVjW1cxFv2wA==
      send_community: true
      maximum_routes: 0
  neighbors:
    172.31.255.16:
      peer_group: IPv4-UNDERLAY-PEERS
    172.31.255.18:
      peer_group: IPv4-UNDERLAY-PEERS
    192.168.255.1:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-SPINE01
      remote_as: 65001
    192.168.255.2:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-SPINE02
      remote_as: 65001
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
  address_family_ipv4:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: false
      IPv4-UNDERLAY-PEERS:
        activate: true
  address_family_rtc: null
  vlan_aware_bundles:
    Tenant_A_APP_Zone:
      rd: 192.168.255.7:12
      route_targets:
        both:
        - '12:12'
      redistribute_routes:
      - learned
      vlan: 130-131
    Tenant_A_DB_Zone:
      rd: 192.168.255.7:13
      route_targets:
        both:
        - '13:13'
      redistribute_routes:
      - learned
      vlan: 140-141
    Tenant_A_OP_Zone:
      rd: 192.168.255.7:10
      route_targets:
        both:
        - '10:10'
      redistribute_routes:
      - learned
      vlan: 110-112
    Tenant_A_WAN_Zone:
      rd: 192.168.255.7:14
      route_targets:
        both:
        - '14:14'
      redistribute_routes:
      - learned
      vlan: 150
    Tenant_A_WEB_Zone:
      rd: 192.168.255.7:11
      route_targets:
        both:
        - '11:11'
      redistribute_routes:
      - learned
      vlan: 120-121
    Tenant_A_VMOTION:
      tenant: Tenant_A
      rd: 192.168.255.7:55160
      route_targets:
        both:
        - 55160:55160
      redistribute_routes:
      - learned
      vlan: 160
    Tenant_A_NFS:
      tenant: Tenant_A
      rd: 192.168.255.7:10161
      route_targets:
        both:
        - 10161:10161
      redistribute_routes:
      - learned
      vlan: 161
    Tenant_B_OP_Zone:
      rd: 192.168.255.7:20
      route_targets:
        both:
        - '20:20'
      redistribute_routes:
      - learned
      vlan: 210-211
    Tenant_B_WAN_Zone:
      rd: 192.168.255.7:21
      route_targets:
        both:
        - '21:21'
      redistribute_routes:
      - learned
      vlan: 250
    Tenant_C_OP_Zone:
      rd: 192.168.255.7:30
      route_targets:
        both:
        - '30:30'
      redistribute_routes:
      - learned
      vlan: 310-311
    Tenant_C_WAN_Zone:
      rd: 192.168.255.7:31
      route_targets:
        both:
        - '31:31'
      redistribute_routes:
      - learned
      vlan: 350
  vlans: null
  vrfs:
    Tenant_A_APP_Zone:
      router_id: 192.168.255.7
      rd: 192.168.255.7:12
      route_targets:
        import:
          evpn:
          - '12:12'
        export:
          evpn:
          - '12:12'
      redistribute_routes:
      - connected
    Tenant_A_DB_Zone:
      router_id: 192.168.255.7
      rd: 192.168.255.7:13
      route_targets:
        import:
          evpn:
          - '13:13'
        export:
          evpn:
          - '13:13'
      redistribute_routes:
      - connected
    Tenant_A_OP_Zone:
      router_id: 192.168.255.7
      rd: 192.168.255.7:10
      route_targets:
        import:
          evpn:
          - '10:10'
        export:
          evpn:
          - '10:10'
      redistribute_routes:
      - connected
    Tenant_A_WAN_Zone:
      router_id: 192.168.255.7
      rd: 192.168.255.7:14
      route_targets:
        import:
          evpn:
          - '14:14'
        export:
          evpn:
          - '14:14'
      redistribute_routes:
      - connected
    Tenant_A_WEB_Zone:
      router_id: 192.168.255.7
      rd: 192.168.255.7:11
      route_targets:
        import:
          evpn:
          - '11:11'
        export:
          evpn:
          - '11:11'
      redistribute_routes:
      - connected
    Tenant_B_OP_Zone:
      router_id: 192.168.255.7
      rd: 192.168.255.7:20
      route_targets:
        import:
          evpn:
          - '20:20'
        export:
          evpn:
          - '20:20'
      redistribute_routes:
      - connected
    Tenant_B_WAN_Zone:
      router_id: 192.168.255.7
      rd: 192.168.255.7:21
      route_targets:
        import:
          evpn:
          - '21:21'
        export:
          evpn:
          - '21:21'
      redistribute_routes:
      - connected
    Tenant_C_OP_Zone:
      router_id: 192.168.255.7
      rd: 192.168.255.7:30
      route_targets:
        import:
          evpn:
          - '30:30'
        export:
          evpn:
          - '30:30'
      redistribute_routes:
      - connected
    Tenant_C_WAN_Zone:
      router_id: 192.168.255.7
      rd: 192.168.255.7:31
      route_targets:
        import:
          evpn:
          - '31:31'
        export:
          evpn:
          - '31:31'
      redistribute_routes:
      - connected
ip_extcommunity_lists: null
router_ospf: null
router_isis: null
queue_monitor_streaming: null
management_api_http:
  enable_https: true
  enable_vrfs:
    MGMT: null
aliases: |-
  alias sarp show ip arp
  alias senz show interface counter error | nz
  alias sib show ip bgp
  alias sibs show ip bgp summary
  alias siib show ip int brief
  alias sir show ip route
  alias smac show mac address-table dynamic
  alias snz show interface counter | nz
  alias spd show port-channel %1 detail all
  alias sps show port-channel summary
  alias sqnz show interface counter queue | nz
  alias srnz show interface counter rate | nz
