switch_platform: vEOS-LAB
switch_mgmt_ip: 10.73.3.1/16
switch_bgp_as: 65001
switch_router_id: 192.168.255.1
switch_evpn_role: server
switch_evpn_route_servers: []
switch_evpn_route_clients:
- DC1-BLEAF1A
- DC1-BLEAF1B
- DC1-LEAF1A
- DC1-LEAF1B
- DC1-LEAF2A
- DC1-LEAF2B
- DC1-LEAF3A
- DC1-LEAF4A
service_routing_protocols_model: multi-agent
ip_routing: true
hardware_counters: null
daemon_terminattr:
  ingestgrpcurl:
    ips:
    - 10.83.31.63
    port: 9910
  ingestauth_key: Arista123
  ingestvrf: MGMT
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: false
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
event_monitor: null
event_handlers: null
load_interval:
  default: 5
queue_monitor_length: null
name_server:
  source:
    vrf: MGMT
  nodes:
  - 10.73.0.1
ntp_server:
  local_interface:
    vrf: MGMT
    interface: Management1
  nodes:
  - 10.73.0.1
redundancy: null
spanning_tree:
  mode: none
aaa_authorization:
  exec:
    default: local
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$qDzD2KQXoyPAYiKW$44OfXUXfvwKXJZcJ4/MOljDk8HxONlzJHjcYGPNxeU0JHvB2fyVBBdhph239vRrFcobF5H3/5J2etJljjhhiQ.
  ansible:
    privilege: 15
    role: network-admin
    sha512_password: $6$/OcMpqcR8opsfwLC$Ui9GUIQH2WcykVQKsbZccT53QN./PWbd2Zn5pipvoqbTJMSE9SWwJnoN5eGq2A/bM9wMcoMrP.nyUDAbgZcLF0
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$qgSkkn4vOILubEVA$eGaW0WVo6ZooKdSAfNMUpZKZ1hSn1cHh5xYIPFsB83C.UIOPg0TRRBoPypKKgEpmhdPdbgOQjh7IazXhtv.191
clock: null
vrfs:
  MGMT:
    ip_routing: false
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3
ethernet_interfaces:
  Ethernet6:
    peer: DC1-BLEAF1A
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-BLEAF1A_Ethernet1
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.24/31
  Ethernet7:
    peer: DC1-BLEAF1B
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-BLEAF1B_Ethernet1
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.28/31
  Ethernet1:
    peer: DC1-LEAF1A
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF1A_Ethernet1
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.0/31
  Ethernet2:
    peer: DC1-LEAF1B
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF1B_Ethernet1
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.4/31
  Ethernet3:
    peer: DC1-LEAF2A
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF2A_Ethernet1
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.8/31
  Ethernet4:
    peer: DC1-LEAF2B
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF2B_Ethernet1
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.12/31
  Ethernet5:
    peer: DC1-LEAF3A
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF3A_Ethernet1
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.16/31
  Ethernet8:
    peer: DC1-LEAF4A
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF4A_Ethernet1
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.20/31
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 192.168.255.1/32
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 10.73.3.1/16
    gateway: 10.73.0.1
tcam_profile: null
platform: null
mac_address_table: null
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.73.0.1
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 192.168.255.0/24 le 32
route_maps:
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
peer_filters: null
router_bgp:
  as: 65001
  router_id: 192.168.255.1
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  - maximum-paths 4 ecmp 4
  peer_groups:
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      peer_filter: LEAF-AS-RANGE
      password: AQQvKeimxJu+uGQ/yYvv9w==
      maximum_routes: 12000
      send_community: true
    EVPN-OVERLAY-PEERS:
      type: evpn
      update_source: Loopback0
      bfd: true
      ebgp_multihop: '3'
      password: q+VNViP5i4rVjW1cxFv2wA==
      send_community: true
      maximum_routes: 0
      next_hop_unchanged: true
  neighbors:
    172.31.255.25:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: 65199
    172.31.255.29:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: 65199
    172.31.255.1:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: 65101
    172.31.255.5:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: 65101
    172.31.255.9:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: 65102
    172.31.255.13:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: 65102
    172.31.255.17:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: 65103
    172.31.255.21:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: 65104
    192.168.255.9:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-BLEAF1A
      remote_as: 65199
    192.168.255.10:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-BLEAF1B
      remote_as: 65199
    192.168.255.3:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-LEAF1A
      remote_as: 65101
    192.168.255.4:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-LEAF1B
      remote_as: 65101
    192.168.255.5:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-LEAF2A
      remote_as: 65102
    192.168.255.6:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-LEAF2B
      remote_as: 65102
    192.168.255.7:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-LEAF3A
      remote_as: 65103
    192.168.255.8:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-LEAF4A
      remote_as: 65104
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
  address_family_ipv4:
    peer_groups:
      IPv4-UNDERLAY-PEERS:
        activate: true
      EVPN-OVERLAY-PEERS:
        activate: false
  address_family_rtc: null
router_ospf: null
router_isis: null
queue_monitor_streaming: null
management_api_http:
  enable_https: true
  enable_vrfs:
    MGMT: null
aliases: |-
  alias sarp show ip arp
  alias senz show interface counter error | nz
  alias sib show ip bgp
  alias sibs show ip bgp summary
  alias siib show ip int brief
  alias sir show ip route
  alias smac show mac address-table dynamic
  alias snz show interface counter | nz
  alias spd show port-channel %1 detail all
  alias sps show port-channel summary
  alias sqnz show interface counter queue | nz
  alias srnz show interface counter rate | nz
