l2leaf_node_group: DC1_L2LEAF1
switch_platform: vEOS-LAB
leaf_id: 1
switch_mgmt_ip: 10.73.3.11/16
leaf_filter_tenants:
- Tenant_A
leaf_filter_tags:
- opzone
- web
- app
leaf_allowed_vrfs:
- Tenant_A_APP_Zone
- Tenant_A_OP_Zone
- Tenant_A_WEB_Zone
leaf_allowed_svis:
- 130
- 131
- 110
- 111
- 112
- 120
- 121
leaf_allowed_vlans:
- 130
- 131
- 110
- 111
- 112
- 120
- 121
leaf_mlag: false
service_routing_protocols_model: multi-agent
ip_routing: true
hardware_counters: null
daemon_terminattr:
  ingestgrpcurl:
    ips:
    - 10.83.31.63
    port: 9910
  ingestauth_key: Arista123
  ingestvrf: MGMT
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: false
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
event_monitor: null
event_handlers: null
load_interval:
  default: 5
queue_monitor_length: null
name_server:
  source:
    vrf: MGMT
  nodes:
  - 10.73.0.1
ntp_server:
  local_interface:
    vrf: MGMT
    interface: Management1
  nodes:
  - 10.73.0.1
redundancy: null
spanning_tree:
  mode: mstp
  mst_instances:
    '0':
      priority: 16384
aaa_authorization:
  exec:
    default: local
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$qDzD2KQXoyPAYiKW$44OfXUXfvwKXJZcJ4/MOljDk8HxONlzJHjcYGPNxeU0JHvB2fyVBBdhph239vRrFcobF5H3/5J2etJljjhhiQ.
  ansible:
    privilege: 15
    role: network-admin
    sha512_password: $6$/OcMpqcR8opsfwLC$Ui9GUIQH2WcykVQKsbZccT53QN./PWbd2Zn5pipvoqbTJMSE9SWwJnoN5eGq2A/bM9wMcoMrP.nyUDAbgZcLF0
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$qgSkkn4vOILubEVA$eGaW0WVo6ZooKdSAfNMUpZKZ1hSn1cHh5xYIPFsB83C.UIOPg0TRRBoPypKKgEpmhdPdbgOQjh7IazXhtv.191
clock: null
vlans:
  130:
    tenant: Tenant_A
    name: Tenant_A_APP_Zone_1
  131:
    tenant: Tenant_A
    name: Tenant_A_APP_Zone_2
  110:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_1
  111:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_2
  112:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_3
  120:
    tenant: Tenant_A
    name: Tenant_A_WEB_Zone_1
  121:
    tenant: Tenant_A
    name: Tenant_A_WEBZone_2
vrfs:
  MGMT:
    ip_routing: false
port_channel_interfaces:
  Port-Channel1:
    description: DC1-LEAF1A_Po5
    type: switched
    shutdown: false
    vlans: 110-112,120-121,130-131
    mode: trunk
ethernet_interfaces:
  Ethernet1:
    peer: DC1-LEAF1A
    peer_interface: Ethernet5
    peer_type: l3leaf
    description: DC1-LEAF1A_Ethernet5
    type: switched
    shutdown: false
    channel_group:
      id: 1
      mode: active
  Ethernet2:
    peer: DC1-LEAF1B
    peer_interface: Ethernet5
    peer_type: l3leaf
    description: DC1-LEAF1B_Ethernet5
    type: switched
    shutdown: false
    channel_group:
      id: 1
      mode: active
  Ethernet5:
    peer: server01
    peer_interface: Eth1
    peer_type: server
    description: server01_Eth1
    type: switched
    shutdown: false
    mode: trunk
    vlans: 110-111
    profile: TENANT_A
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 10.73.3.11/16
    gateway: 10.73.0.1
vlan_interfaces: null
tcam_profile: null
platform: null
mac_address_table: null
ip_igmp_snooping:
  globally_enabled: true
  vlans: null
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.73.0.1
queue_monitor_streaming: null
management_api_http:
  enable_https: true
  enable_vrfs:
    MGMT: null
aliases: |-
  alias sarp show ip arp
  alias senz show interface counter error | nz
  alias sib show ip bgp
  alias sibs show ip bgp summary
  alias siib show ip int brief
  alias sir show ip route
  alias smac show mac address-table dynamic
  alias snz show interface counter | nz
  alias spd show port-channel %1 detail all
  alias sps show port-channel summary
  alias sqnz show interface counter queue | nz
  alias srnz show interface counter rate | nz
