---
# Validation lab
# local users
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$qDzD2KQXoyPAYiKW$44OfXUXfvwKXJZcJ4/MOljDk8HxONlzJHjcYGPNxeU0JHvB2fyVBBdhph239vRrFcobF5H3/5J2etJljjhhiQ."

  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$qgSkkn4vOILubEVA$eGaW0WVo6ZooKdSAfNMUpZKZ1hSn1cHh5xYIPFsB83C.UIOPg0TRRBoPypKKgEpmhdPdbgOQjh7IazXhtv.191"

  ansible:
    privilege: 15
    role: network-admin
    sha512_password: "$6$/OcMpqcR8opsfwLC$Ui9GUIQH2WcykVQKsbZccT53QN./PWbd2Zn5pipvoqbTJMSE9SWwJnoN5eGq2A/bM9wMcoMrP.nyUDAbgZcLF0"

# Cloud Vision server information
cvp_instance_ip: 10.83.31.63
cvp_ingestauth_key: "Arista123"

# OOB Management network default gateway.
mgmt_gateway: 10.73.0.1

# dns servers.
name_servers:
  - 10.73.0.1

dns_domain: "lon.aristanetworks.com"

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
ntp_servers:
  - 10.73.0.1

custom_structured_configuration_load_interval:
  default: 5

aaa_authentication:
  policies:
    local:
      allow_nopassword: true

custom_structured_configuration_aaa_authorization:
  exec:
    default: "local"

custom_structured_configuration_aliases: |
  alias sarp show ip arp
  alias senz show interface counter error | nz
  alias sib show ip bgp
  alias sibs show ip bgp summary
  alias siib show ip int brief
  alias sir show ip route
  alias smac show mac address-table dynamic
  alias snz show interface counter | nz
  alias spd show port-channel %1 detail all
  alias sps show port-channel summary
  alias sqnz show interface counter queue | nz
  alias srnz show interface counter rate | nz

# custom_structured_configuration_snmp_server:
#   contact: "Sean"
#   location: "Somewhere in London town"
#   hosts:
#     - host: 10.73.0.1
#       vrf: "MGMT"
#       users:
#         - username: admin
#           authentication_level: noauth
#           version: 2c
#   traps:
#     enable: true
#   vrfs:
#     - name: MGMT
#       enable: true
#   users:
#     - name: admin
#       group: none
#       version: 2c
#       auth: < hash_algorithm >
#       auth_passphrase: < encrypted_auth_passphrase >