---
port_profiles:
  TENANT_A_B:
    mode: trunk
    vlans: "110-112,120"
    spanning_tree_portfast: edge
  TENANT_A:
    mode: trunk
    vlans: "110-111,114"
    spanning_tree_portfast: edge
  TENANT_B:
    mode: trunk
    vlans: "210-211"

servers:
  server01:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [Eth1]
        switch_ports: [Ethernet5]
        switches: [DC1-L2LEAF1A]
        profile: TENANT_A
  server02:
    rack: RackB
    adapters:
      - type: nic
        server_ports: [Eth1]
        switch_ports: [Ethernet5]
        switches: [DC1-L2LEAF2A]
        profile: TENANT_A
  server03:
    rack: RackC
    adapters:
      - type: nic
        server_ports: [Eth1,Eth2]
        switch_ports: [Ethernet7,Ethernet7]
        switches: [DC1-LEAF3A,DC1-LEAF4A]
        profile: TENANT_A
        port_channel:
          description: PortChanne1
          mode: active
          short_esi: 0303:0202:0101