---
port_profiles:
  TENANT_A_B:
    mode: trunk
    vlans: "110-111,210-211"
  TENANT_A:
    mode: trunk
    vlans: "110-111"
  TENANT_B:
    mode: trunk
    vlans: "210-211"

servers:
  server01:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [Eth1]
        switch_ports: [Ethernet5]
        switches: [DC1-L2LEAF1A]
        profile: TENANT_A
  server02:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [Eth1]
        switch_ports: [Ethernet5]
        switches: [DC1-L2LEAF2A]
        profile: TENANT_A
